// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)
import BestselectController from "./bestselect_controller"
application.register("bestselect", BestselectController)
import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)
import StepFormController from "./step_form_controller"
application.register("step-form", StepFormController)
